baseURL = "https://lq7.tw/"
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
title = "LQ7的思考與閒聊"
theme = "PaperMod"
timeZone = "Asia/Taipei"
hasCJKLanguage = true
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.renderHooks.image]
  useEmbedded = 'fallback'
[pagination]
  pagerSize = 50

[params]
  author = "LQ7"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true
  ShowFullTextinRSS = true
  ShowWordCount = true
  mainSections = ["fanfic", "writing", "reading", "thinking", "mood","tech","event","music","photo"]
  defaultImage = "https://lq7.tw/images/anosoyo.png"
  math = true
  
  [params.label]
  text = "LQ7的思考與閒聊"
  icon = "/images/avatar.png"
  iconHeight = 35

  [params.homeInfoParams]

[params.footer]
  hidePoweredBy = true
  text = "LQ7 版權所有"

[menu]
  [[menu.main]]
    name = "全部"
    url = "/list/"
    weight = 5
  [[menu.main]]
    name = "小說"
    url = "/fanfic/"
    weight = 10
	
  [[menu.main]]
    name = "閒聊"
    url = "/chat/"
    weight = 15
	
  [[menu.main]]
    name = "思考"
    url = "/thinking/"
    weight = 20
	
  [[menu.main]]
    name = "留言"
    url = "/guestbook/"
    weight = 55

  [[menu.main]]
    name = "關於"
    url = "/about/"
    weight = 60
